### PR TITLE
If cache does not exist, write it from scope instead of acting on 0

### LINKED ISSUE #12: If real value is not cached, increment/decrement create wrong result
If the value has not been accessed before updating, there is no cache. The implications are:

- Instead of real value + 1, it's 1 (or -1)
- Expiration is not set on the key

### PR DESCRIPTION
**Pull request by Gargron**
Fix #12

### CODE REVIEW

**Comment by Gargron** [comment]
>Failure/Error: ActiveSupport.halt_callback_chains_on_return_false = false
>NoMethodError:
>  undefined method `halt_callback_chains_on_return_false=' for ActiveSupport:Module

Did I do this?! :eyes:

**Comment by iguchi1124** [comment]
> Did I do this?! 👀

Sorry, I will check this error soon.

**Review by iguchi1124 — APPROVED** [review]
looks good!

**Comment by Gargron** [comment]
I've run the tests locally:

```
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /home/eugr/Projects/counter_cache-rails/spec/dummy/config/initializers/new_framework_defaults.rb:21)
..............

Finished in 0.26176 seconds (files took 5.03 seconds to load)
14 examples, 0 failures
```

**Pull request merged**
